# Site
title:              CS2 MULCH
bio:                'Physical Manipulatives and Games for CS2 Data Structure Classrooms'
description:        "Physical Manipulatives and Games for CS2 Data Structure Classrooms"
locale:             en_US
baseurl: "/cs2mulch" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             "mgoadric/cs2mulch"

# personal
location:           Conway, AR
phone:              501-450-1367
email:              goadrich@hendrix.edu # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /cs2mulch/images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
